### ISSUE TITLE
Share and votes doesnt work

### ISSUE THREAD

**Issue by abbbcccaa** [JamesTheHacker/Facebook-Live-Reactions#10]
![chrome_2016-11-23_11-10-54](https://cloud.githubusercontent.com/assets/8458809/20557849/8936a3e0-b16d-11e6-9d4a-45058cf5ae20.jpg)

`[23-Nov-2016 10:03:06 UTC] PHP Warning:  join(): Invalid arguments passed in /root/facebook-live-reactions/functions.php on line 14
[23-Nov-2016 10:03:06 UTC] PHP Notice:  Undefined index: data in /root/facebook-live-reactions/fblive.php on line 57
[23-Nov-2016 10:03:06 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, null given in /root/facebook-live-reactions/fblive.php on line 63
[23-Nov-2016 10:03:07 UTC] PHP Notice:  Use of undefined constant SETTINGS - assumed 'SETTINGS' in /root/facebook-live-reactions/functions.php on line 114
[23-Nov-2016 10:03:07 UTC] PHP Warning:  Illegal string offset 'REACTIONS' in /root/facebook-live-reactions/functions.php on line 114
[23-Nov-2016 10:03:07 UTC] PHP Warning:  array_keys() expects parameter 1 to be array, string given in /root/facebook-live-reactions/functions.php on line 114
[23-Nov-2016 10:03:07 UTC] PHP Warning:  Invalid argument supplied for foreach() in /root/facebook-live-reactions/functions.php on line 71`

How to fix it?

**Comment by ryanwhittaker** [comment]
A lot of these data validation checks should be fixed in #8 which'll be merged shortly. 

Thats some weird errors in that stacktrace though. There's no reason for

`[23-Nov-2016 10:03:07 UTC] PHP Notice: Use of undefined constant SETTINGS - assumed 'SETTINGS' in /root/facebook-live-reactions/functions.php on line 114`
or
`[23-Nov-2016 10:03:06 UTC] PHP Warning: join(): Invalid arguments passed in /root/facebook-live-reactions/functions.php on line 14`
Unless you've renamed, moved or corrupted the `settings.php` file in your root directory. Ensure when you changed the APP_SECRET, KEY and POST_ID, you didn't accidentally strip one of the trailing commas.

**Comment by abbbcccaa** [comment]
All commas are okay, so after update it will works?

**Comment by JamesTheHacker** [comment]
What version of PHP are you using? I believe array constants are only supported in version 7.

**Comment by abbbcccaa** [comment]
5.6.27-0+deb8u1
but on the info page there is information that script will work with 5.6

**Comment by JamesTheHacker** [comment]
@ryanwhittaker maybe we should use `const SETTINGS = ...`? 

@lanceq1337 I will hopefully merging tonight when I get back from work. I've got a quick change to make. I will also test fully on 5.6 to ensure it works. I wanted to ideally move away from older versions but it seems a lot of people are still using it.

Thoughts and input welcomed ...

**Comment by abbbcccaa** [comment]
Thanks, waiting for update:)

**Comment by ryanwhittaker** [comment]
@JamesTheHacker Don't think we can use const for that. We can define it the same way we do in `fblive.php` instead, and then use `global` in the function scopes to bring the variable in. That would work I believe. ex:

```php
$settings = include __DIR__ . '/settings.php';
// stuff

function reactionCount($fb, $objectID, $accessToken)
{
    global $settings;
    foreach ($settings['REACTIONS'] as $key => $position) {
        $fields[] = "reactions.type({$key}).limit(0).summary(total_count).as({$key})";
    }
    // stuff
}
```

OR

```php
$settings = include __DIR__ . '/settings.php';
// stuff

function reactionCount($fb, $objectID, $accessToken)
{
    foreach ($GLOBALS['settings']['REACTIONS'] as $key => $position) {
        $fields[] = "reactions.type({$key}).limit(0).summary(total_count).as({$key})";
    }
    // stuff
}
```
I thought constant arrays were a 5.6, but it seems the define syntax is 7.0...: http://php.net/manual/en/language.constants.syntax.php

```php
// Works as of PHP 7
define('ANIMALS', array('dog','cat', 'bird'));
```

I'll leave it in your hands if you just want to support just 7, or go back to 5.5,5.6. Its probably worth covering the older versions though since its a pretty minor thing that pushed that req.

**Comment by JamesTheHacker** [comment]
I think for now it would be better to support 5.5. 7 would be nice but I've got a feeling a lot of issues will be raised. Soon as I'm back from work I'll get down to fixing and hopefully merging tonight.

**Comment by abbbcccaa** [comment]
Any news:)?

**Comment by JamesTheHacker** [comment]
@lanceq1337 Yes buddy, I'm on the case now. Should be done in a couple of hours. I was due to do this last night but I got caught up at work. Thank you for your patience.

**Comment by abbbcccaa** [comment]
Okay, waiting :)

**Comment by abbbcccaa** [comment]
Bump

**Comment by JamesTheHacker** [comment]
Done. Waiting to merge.
