### ISSUE TITLE
Facebook api doesnt return all comments

### ISSUE THREAD

**Issue by randinfo** [JamesTheHacker/Facebook-Live-Reactions#14]
Hi tried the new version and the old one in master branch. And both seems to not retrieving all the coments of the post ID. It's realy strange. And cause of that the people that are commenting the keyword dont show theire names... it's weird

I used [facebook debuger](https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=1798847323697722%2Fcomments%3Ffilter%3Dstream%26order%3Dreverse_chronological&version=v2.8)

**Comment by JamesTheHacker** [comment]
How active are the comment feeds? If there's high activity a few may be missed. This is because the Facebook API doesn't return the full list of comments. The comments are paginated. We only grab the first page. We then filter the comments and extract those that contain the keyword. This happens every 5 seconds.

There's a new update waiting to be merged. I hope to merge tonight. I've tested this end and all works fine. Try it and let me know.
