### ISSUE TITLE
Problem while streaming

### ISSUE THREAD

**Issue by randinfo** [JamesTheHacker/Facebook-Live-Reactions#4]
I got good bitrate
frame= 6465 fps= 25 q=-1.0 Lsize=   65216kB time=00:04:18.63 bitrate=2065.7kbits/s
but in the feacebook page i got a message saying that my live is over when i click in it.
But there is the "broadcasting" header...

And if i stream an mp4 file thru facebook it's ok...

Any idea ?

**Comment by ryanwhittaker** [comment]
Hmm... I can't get this to repeat. You are maintaining the stream in a separate console tab right? You must use the `fblive.sh` script to run the stream, while using `fblive.php` to rebuild the assets. If you cancel `fblive.sh` to start the php file, it will end the livestream.

**Comment by JamesTheHacker** [comment]
@randinfo It sounds like you're not streaming any audio. If you stream without audio it will show a preview whilst setting up the live stream, but once you "Go Live" Facebook will end the stream. If you don't want audio you can stream silence. Also ensure your audio file is at least 4 hours in length.

Please let me know if this isn't the case. I'm also having trouble replicating.

**Comment by randinfo** [comment]
Hi, thanks for your replies.
@ryanwhittaker i used 3 console tabs. (1 for editing the fblive.sh, 1 for fblive.sh and the other for fblive.php). And i never stoped the stream since i started it. 

I've created an empty mp3 file with zero byte inside it. @JamesTheHacker you think it's the source of the problem ? If i don't wont any sound what are the modifications i have to do ?

And i've edited the fblive.sh to increase the bitrate cause 400kbits/s isnt enought for that resolution i think. I've got 100Mb as output bandwidth i'll use it 😄

**Comment by JamesTheHacker** [comment]
@randinfo you will need to create an audio file that contains data. You can create 4 hours worth of silence pretty easily like so (you must have SoX installed):

First create 1 minute of silence (turn microphone off, or mute it):

    rec audio.mp3 trim 0 60

Then loop that to create 4 hours worth of silence (240 minutes = 4 hours):

    sox audio.mp3 audio-loop.mp3 repeat 240

I am not sure if the issue is with `ffmpeg` or Facebook. I've had similar issues in the past with OBS. I'll look into it more to see if there's a better solution. I would have included 4 hours worth of silence into the repo, but that's going to increase the size dramatically.

Give that a try and let me know how it goes.

**Comment by randinfo** [comment]
Ok i'l give it a try this evening and give you feedback 😃  Thanks.

**Comment by randinfo** [comment]
That solved this issue but i got another issu. Thanks
